### ISSUE TITLE
[Editor] layout issue (aesthetic, minor issue)

### ISSUE THREAD

**Issue by AeSix** [lucko/LuckPermsWeb#75] opened 2019-01-24 19:28 UTC
When permission entries contain long strings, such as a large shorthand node, the permissions display area overruns the editor width.  This has caused the delete and edit buttons to appear off screen with a *normal* width browser window. My window initially cut off in the middle of the "contexts" column. My browser is around 90% the width of my 1920x1200 monitor, so about 1700 pixels wide.

This affects Chrome.  I do not know if it affects other browsers. 

Images speak volumes, so:
![2e9fa0aa31](https://user-images.githubusercontent.com/5191757/51703259-e9ad5980-1fe3-11e9-9592-ed4e56c63dea.png)

**Comment by Turbotailz** [comment] 2019-11-26 05:27
This should be fixed in v2. Please update to LuckPerms v5 to use it and see if the problem is resolved (will close this in the meantime).

**Closed by Turbotailz** 2019-11-26 05:27 UTC
Labels: bug
