### ISSUE TITLE
Worlds?

### ISSUE THREAD

**Issue by FreedTapstry21** [lucko/LuckPermsWeb#134] opened 2020-01-26 18:47 UTC
Where can you do perms for worlds in the BETA website?
please let me know!

**Comment by Andre601** [comment] 2020-01-26 19:27
Click either on the "Add context" button when adding a perm or click on the field in the Context column of a permission when editing it.
There, set world as the key and the name of the world as your value.

**Comment by Turbotailz** [comment] 2020-01-28 05:49
I plan to make this a bit more intuitive - duplicate of #108

**Closed by Turbotailz** 2020-01-28 05:49 UTC
