### ISSUE TITLE
webstie doesnt respond after deleting a permission

### ISSUE THREAD

**Issue by Yuval270** [lucko/LuckPermsWeb#111] opened 2019-12-10 15:01 UTC
agian, title says it all

**Comment by BrainStone** [comment] 2019-12-10 15:50
In #110 you said you can’t delete them. What is it now?

**Comment by Turbotailz** [comment] 2019-12-10 21:39
These have to be the most vague issues I've ever seen.

Mind sharing a bit more info? Maybe a link to your editor session? How can you expect us to have any idea on the problem when all you say is "title says it all"?

**Comment by Turbotailz** [comment] 2019-12-12 00:02
Duplicate of #102

**Closed by Turbotailz** 2019-12-12 00:02 UTC
