### ISSUE TITLE
Permission Description

### ISSUE THREAD

**Issue by hellot1m** [lucko/LuckPermsWeb#323] opened 2020-09-27 23:59 UTC
**Description**
A way to view each permissions built in description.

**Proposed behaviour**
My thought would be when you hover your mouse over the permission name, it gives you a description of what the permission does. This text is typically already built into each plugin, so you would just need to be able to pull this information within the web editor.

Another way, would be to add a new text box to the right of the permission. There's plenty of empty room to fit this in. You could have the description auto populate there. In both the bottom search bar area and after applying it to right as well.

A few other people on the discord gave some interesting ways this could be implemented too, like using Ctrl+t while over the permission.

**Comment by Turbotailz** [comment] 2020-10-08 04:03
While it sounds like a neat idea it is going to be incredibly difficult to gather descriptions of every single permission. I am going to close this as it is very unlikely to be done on the editor side.

**Closed by Turbotailz** 2020-10-08 04:03 UTC

**Comment by hellot1m** [comment] 2020-10-08 15:23
You don't have to do that.... The descriptions are already in the permissions. You just have to add a feature to pull those descriptions. A few other permission plugins already include this feature. 

Check out ultra permissions for a great example of how this is done.

**Comment by underscore11code** [comment] 2020-10-08 15:49
Keep in mind that this would be possibly doubling the amount of data that gets transferred upon editor creation/load. Obviously, that will affect the load times significantly. In addition, few enough plugins register their perms in `plugin.yml`, fewer still include a description.

> Check out ultra permissions for a great example of how this is done.

While UPerms is closed source and thus we can't actually, it's exceedingly simple. They just have a big database of perms mapped to description, and their plugin queries that. The problem is the actual database contents. Short of blatantly copying their db (I assume Tech wouldn't like that), we'd need a long time to build the data to a point where it's actually worth using.

**Comment by hellot1m** [comment] 2020-10-08 16:07
How were they able to easily grab the description from my plugin without anyone ever using it before?

I've also only ever ran into 1 plugin that didn't have a description but that was on the devs end nothing to do with uperms. Although I'm sure they may group in a database, I don't think they store the database remotely. Maybe locally in a h2 format or mysql which is what I used. 

The text from let's say, 100 plugins would only be just a few kilobytes of data. If the luckperms plugin could pull that information on a per server basis and store it on the server owners desired database storage option, then when edit boots up, all it would have to do is pull a single text document up with the pulled information. 

For example:
Plugin1 includes

Line 1: #allows player to use command
Line 2: "example.what.command"

Luckperms already pulls the permission. Just now needs to pull the description and store it locally for the player and editor to pull from. 

A simple text document of less than half a megabyte wouldn't cause that much noticable lag. 

I'd say just try a few ideas and see for yourself. I feel you guys are overcomplicating it and giving up too easily and I may be over simplifying it and not fully understanding. 

But just because uperms does it one way, doesn't mean there isn't a better way. 
If they use a big database on their side, then good for them. I think a local database or one on a mysql server would be a much better more efficient place. And have luckperms.jar do the actual pulling on initial boot. Only has to happen once on the server side unless a new plugin is introduced later, then it would just add to it.

**Comment by Turbotailz** [comment] 2020-10-08 20:02
Either way it's impossible to do this on the editor without the plugin
sending the data in the first place.

**Comment by BrainStone** [comment] 2020-10-08 20:23
Then have the plugin send the data?

I mean there's 0 issue with that. The additional data size is neglicable.  
And most plugins provide descriptions, shockingly enough.

**Comment by Turbotailz** [comment] 2020-10-08 21:39
This is not the right repo to raise the issue, is what I'm saying.

https://github.com/lucko/LuckPerms
